# Generated by Django 4.0.5 on 2022-06-13 14:08

from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0004_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='documents',
            field=models.FileField(blank=True, upload_to=patients.models.get_upload_to),
        ),
    ]
